"""
NetReaper - Test configuration and shared fixtures
Auto-generated by Debug Agent
Author: 09azo14 | License: MIT
"""

import pytest
import tempfile
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))


@pytest.fixture
def mock_console(monkeypatch):
    """Mock rich Console to suppress output during tests."""
    mock = MagicMock()
    monkeypatch.setattr("rich.console.Console.print", MagicMock())
    monkeypatch.setattr("rich.console.Console.input", MagicMock(return_value=""))
    return mock


@pytest.fixture
def temp_dir(tmp_path):
    """Provide a temporary directory for test files."""
    return tmp_path


@pytest.fixture
def mock_subprocess_run():
    """Mock subprocess.run that always succeeds."""
    with patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout="mock output\n",
            stderr=""
        )
        yield mock_run


@pytest.fixture
def mock_subprocess_run_fail():
    """Mock subprocess.run that always fails."""
    with patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(
            returncode=1,
            stdout="",
            stderr="Error: command failed"
        )
        yield mock_run


@pytest.fixture
def mock_popen():
    """Mock subprocess.Popen for streaming command tests."""
    with patch("subprocess.Popen") as mock_popen:
        mock_proc = MagicMock()
        mock_proc.stdout = iter(["line1\n", "open port found\n", "error occurred\n"])
        mock_proc.wait.return_value = 0
        mock_proc.returncode = 0
        mock_popen.return_value = mock_proc
        yield mock_popen


@pytest.fixture
def sample_logger(tmp_path):
    """Create a SessionLogger pointing to a temp directory."""
    with patch("core.logger.REPORTS_DIR", tmp_path):
        from core.logger import SessionLogger
        logger = SessionLogger()
        yield logger
        logger.close()


@pytest.fixture
def mock_shutil_which():
    """Mock shutil.which to simulate tools being installed."""
    installed_tools = {
        "nmap": "/usr/bin/nmap",
        "john": "/usr/bin/john",
        "tshark": "/usr/bin/tshark",
    }
    with patch("shutil.which", side_effect=lambda t: installed_tools.get(t)):
        yield installed_tools


@pytest.fixture
def mock_questionary():
    """Mock questionary to avoid interactive prompts in tests."""
    with patch("questionary.select") as mock_select, \
         patch("questionary.confirm") as mock_confirm, \
         patch("questionary.text") as mock_text:
        mock_select.return_value.ask.return_value = "back"
        mock_confirm.return_value.ask.return_value = True
        mock_text.return_value.ask.return_value = ""
        yield {
            "select": mock_select,
            "confirm": mock_confirm,
            "text": mock_text,
        }


@pytest.fixture
def mock_platform_linux(monkeypatch):
    """Force platform detection to Linux."""
    monkeypatch.setattr("platform.system", lambda: "Linux")
    monkeypatch.setattr("core.platform.get_os", lambda: "linux")


@pytest.fixture
def captured_stdout():
    """Capture stdout during a test."""
    from io import StringIO
    import sys
    old_stdout = sys.stdout
    captured = StringIO()
    sys.stdout = captured
    yield captured
    sys.stdout = old_stdout
